<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="1" ignored="0" total="7" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="360" started-at="2019-12-19T14:22:57Z" finished-at="2019-12-19T14:22:58Z">
    <groups>
    </groups>
    <test name="Basic" duration-ms="204" started-at="2019-12-19T14:22:57Z" finished-at="2019-12-19T14:22:57Z">
      <class name="testNG.TestNG_Basics">
        <test-method status="SKIP" signature="Fail()[pri:0, instance:testNG.TestNG_Basics@39aeed2f]" name="Fail" duration-ms="40" started-at="2019-12-19T14:22:57Z" finished-at="2019-12-19T14:22:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected not achieved expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected not achieved expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at testNG.TestNG_Basics.Fail(TestNG_Basics.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Fail -->
        <test-method status="SKIP" signature="Fail()[pri:0, instance:testNG.TestNG_Basics@39aeed2f]" name="Fail" duration-ms="0" started-at="2019-12-19T14:22:57Z" finished-at="2019-12-19T14:22:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected not achieved expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected not achieved expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at testNG.TestNG_Basics.Fail(TestNG_Basics.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Fail -->
        <test-method status="SKIP" signature="Fail()[pri:0, instance:testNG.TestNG_Basics@39aeed2f]" name="Fail" duration-ms="0" started-at="2019-12-19T14:22:57Z" finished-at="2019-12-19T14:22:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected not achieved expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected not achieved expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at testNG.TestNG_Basics.Fail(TestNG_Basics.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Fail -->
        <test-method status="FAIL" signature="Fail()[pri:0, instance:testNG.TestNG_Basics@39aeed2f]" name="Fail" duration-ms="12" started-at="2019-12-19T14:22:57Z" finished-at="2019-12-19T14:22:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected not achieved expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected not achieved expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at testNG.TestNG_Basics.Fail(TestNG_Basics.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Fail -->
        <test-method status="SKIP" signature="skiptest()[pri:1, instance:testNG.TestNG_Basics@39aeed2f]" name="skiptest" duration-ms="4" started-at="2019-12-19T14:22:57Z" finished-at="2019-12-19T14:22:57Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[This method is not ready yet!!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: This method is not ready yet!!!
at testNG.TestNG_Basics.skiptest(TestNG_Basics.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skiptest -->
        <test-method status="PASS" signature="print()[pri:3, instance:testNG.TestNG_Basics@39aeed2f]" name="print" duration-ms="8" started-at="2019-12-19T14:22:57Z" finished-at="2019-12-19T14:22:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- print -->
      </class> <!-- testNG.TestNG_Basics -->
    </test> <!-- Basic -->
    <test name="Basic1" duration-ms="12" started-at="2019-12-19T14:22:57Z" finished-at="2019-12-19T14:22:58Z">
      <class name="testNG.TestNG1_basics">
        <test-method status="PASS" signature="addition()[pri:0, instance:testNG.TestNG1_basics@7cd62f43]" name="addition" duration-ms="4" started-at="2019-12-19T14:22:57Z" finished-at="2019-12-19T14:22:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addition -->
      </class> <!-- testNG.TestNG1_basics -->
    </test> <!-- Basic1 -->
  </suite> <!-- Suite -->
</testng-results>
